apiVersion: v1
kind: Secret
metadata:
  name: {{ template "v2ray.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "v2ray.name" . }}
    chart: {{ template "v2ray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  config.json: |
    {{- tpl (toJson .Values.config) . | nindent 4 }}