apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}-config
  labels:
    {{- include "xray.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- tpl (toJson .Values.config) . | nindent 4 }}